### ISSUE TITLE
How to Test

### ISSUE THREAD

**Issue by debojit369db** [igrigorik/spdy#20]
HI, 

I need some help. We are having one SPDY library which can be integrated in server and Client. How we can test the library. How to create a Client and Server using possible scripting or if anybody can give some idea it will be helpful.

**Comment by igrigorik** [comment]
You can see the specs here to get you started: https://github.com/igrigorik/spdy/tree/master/spec

Note that current code is using outdated SPDY protocol and needs to be updated to v3.
