### ISSUE TITLE
Few Questions

### ISSUE THREAD

**Issue by Brijendrasial** [igrigorik/spdy#21]
Hello Sir,

Please take your time to answer the question below.

1) Is there any module for cpanel installation available?
2) can we run mod_spdy and mod_pagespeed together? If yes how its gona help? because we can use ssl support in mod_pagespeed too?
3) mod_spdy reduces page load time, even mod_pagespeed does that too by compressing, minifying and etc etc. So whats the difference?
4) Its for ssl (https) website optimization, doe it optimize non ssl too?

**Comment by igrigorik** [comment]
@Brijendrasial these questions have nothing to do with the SPDY gem.. Closing the bug, but a few answers below.

1) mod_spdy is available for Apache, but no CPanel integration (shouldn't be hard to build)
2) yes, you can run both - check documentation on mod_pagespeed site.
3) they're not exclusive. SPDY is focused on transport performance, PageSpeed can help with structure.
4) no, you will need HTTPS for NPN negotiation.
