### ISSUE TITLE
Cannot load page with the sample server

### ISSUE THREAD

**Issue by zhenyu-zhou** [igrigorik/spdy#22]
Hello,

I'm trying to load the sample server but it just blocked forever and nothing came out in my Chrome.  Could you please help me with that?

I load the server and Chrome as suggested (they work well after installing eventmachine by "sudo gem install eventmachine"):
ruby spdy_server.rb 
/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --use-spdy=ssl

But when I trying to load the site (eg, https://skylynx.cs.duke.edu:10000), it keeps loading and nothing shows up. The log on the server side is:
[:received, "\x16\x03\x01\x00\xD3\x01\x00\x00\xCF\x03\x03\x88\x89\xD3\xDB\xEAX\xFD\xAC=\xDE/\x1C\xC3\x0F\xC59\xC1\xD2\xEB\x92\xF62\x88O\x17\xCC\xD6\x11\xA6]A\x8B\x00\x00\"\xC0+\xC0/\x00\x9E\xCC\x14\xCC\x13\xCC\x15\xC0\n\xC0\x14\x009\xC0\t\xC0\x13\x003\x00\x9C\x005\x00/\x00\n\x00\xFF\x01\x00\x00\x84\x00\x00\x00\x18\x00\x16\x00\x00\x13skylynx.cs.duke.edu\x00\x17\x00\x00\x00#\x00\x00\x00\r\x00\x16\x00\x14\x06\x01\x06\x03\x05\x01\x05\x03\x04\x01\x04\x03\x03\x01\x03\x03\x02\x01\x02\x03\x00\x05\x00\x05\x01\x00\x00\x00\x003t\x00\x00\x00\x12\x00\x00\x00\x10\x00\x1D\x00\e\bhttp/1.1\bspdy/3.1\x05h2-14\x02h2uP\x00\x00\x00\v\x00\x02\x01\x00\x00\n\x00\x06\x00\x04\x00\x17\x00\x18"]
[:received, "\x16\x03\x01\x00\xD3\x01\x00\x00\xCF\x03\x03\x12\xC4L\xA12W*\x10,\xF7>5\x8F\xAB\xD02\x00\x81\xE4v\xD4%\xB2\xFC_\xE9\xC5\x02\xD7\xA8\xDA\xF7\x00\x00\"\xC0+\xC0/\x00\x9E\xCC\x14\xCC\x13\xCC\x15\xC0\n\xC0\x14\x009\xC0\t\xC0\x13\x003\x00\x9C\x005\x00/\x00\n\x00\xFF\x01\x00\x00\x84\x00\x00\x00\x18\x00\x16\x00\x00\x13skylynx.cs.duke.edu\x00\x17\x00\x00\x00#\x00\x00\x00\r\x00\x16\x00\x14\x06\x01\x06\x03\x05\x01\x05\x03\x04\x01\x04\x03\x03\x01\x03\x03\x02\x01\x02\x03\x00\x05\x00\x05\x01\x00\x00\x00\x003t\x00\x00\x00\x12\x00\x00\x00\x10\x00\x1D\x00\e\bhttp/1.1\bspdy/3.1\x05h2-14\x02h2uP\x00\x00\x00\v\x00\x02\x01\x00\x00\n\x00\x06\x00\x04\x00\x17\x00\x18"]
// NOTE: I force to stop it here
^C[:SPDY, :connection_closed]
[:SPDY, :connection_closed]
/var/lib/gems/1.9.1/gems/eventmachine-1.0.7/lib/eventmachine.rb:187:in `run_machine': Interrupt
    from /var/lib/gems/1.9.1/gems/eventmachine-1.0.7/lib/eventmachine.rb:187:in`run'
    from spdy_server.rb:46:in `<main>'

If I load the page by HTTP, the log is:
[:received, "GET / HTTP/1.1\r\nHost: skylynx.cs.duke.edu:10000\r\nConnection: keep-alive\r\nAccept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,_/_;q=0.8\r\nUser-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.124 Safari/537.36\r\nAccept-Encoding: gzip, deflate, sdch\r\nAccept-Language: en-US,en;q=0.8,zh-CN;q=0.6,zh;q=0.4\r\nCookie: _ga=GA1.2.1167807627.1431234950; __utma=21592105.818721158.1427254610.1431462933.1432241088.5; __utmz=21592105.1432241088.5.3.utmcsr=google|utmccn=(organic)|utmcmd=organic|utmctr=(not%20provided); FBJSC=1422565286; ywandp=10001806365479%3A1310147723\r\n\r\n"]
[:SPDY, :connection_closed]
[:received, "GET / HTTP/1.1\r\nHost: skylynx.cs.duke.edu:10000\r\nConnection: keep-alive\r\nAccept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,_/_;q=0.8\r\nUser-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.124 Safari/537.36\r\nAccept-Encoding: gzip, deflate, sdch\r\nAccept-Language: en-US,en;q=0.8,zh-CN;q=0.6,zh;q=0.4\r\nCookie: _ga=GA1.2.1167807627.1431234950; __utma=21592105.818721158.1427254610.1431462933.1432241088.5; __utmz=21592105.1432241088.5.3.utmcsr=google|utmccn=(organic)|utmcmd=organic|utmctr=(not%20provided); FBJSC=1422565286; ywandp=10001806365479%3A1310147723\r\n\r\n"]
^C[:SPDY, :connection_closed]
/var/lib/gems/1.9.1/gems/eventmachine-1.0.7/lib/eventmachine.rb:187:in `run_machine': Interrupt
    from /var/lib/gems/1.9.1/gems/eventmachine-1.0.7/lib/eventmachine.rb:187:in`run'
    from spdy_server.rb:46:in `<main>'

Because the thread is terminated at eventmachine, I guess I may install an incompatible version. Is it correct and any other ideas with this issue?

Many thanks!

**Comment by igrigorik** [comment]
@zhenyu-zhou SPDY will be deprecated by Chrome in early 2016. I'd recommend you move to HTTP/2. See ruby example here: https://github.com/igrigorik/http-2/tree/master/example

**Comment by zhenyu-zhou** [comment]
@igrigorik Thanks for your reply! I just tried the HTTP/2 server/client and they work well. But I'm wondering whether the server can be connected by a browser (eg. chrome)? (I'll post this issue at that repository as well).

And one further question, if HTTPS/2 will replace SPDY, what role will QUIC take? Will it be used together with HTTP/2 or is it just an experimental protocol liks SPDY?

Thanks!

**Comment by igrigorik** [comment]
Re, QUIC: the short answer is.. it is an experimental protocol, so TBD.

I'll follow up on your http/2 question in the other repo.
